name: CI
on:

  workflow_dispatch:
    inputs:
      image:
        type: string
        description: Specify container image to scan
        required: true

permissions:
      id-token: write
      contents: read
      pull-requests: write

jobs:
  trivy:
    name: 'Trivy Scan'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1
    
    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: 'AZ ACR login'
      run: az acr login --name ${{ secrets.AZURE_ACR_NAME }}

    - name: trivy
      uses: aquasecurity/trivy-action@0.16.0
      with:
        image-ref: ${{ github.event.inputs.image }}
        scan-type: 'image'
        format: json
        output: report.json
        exit-code: 1
        vuln-type: os
        severity: 'CRITICAL,HIGH'
        ignore-unfixed: true
        #ignore-policy: true
        #github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Trivy Report
      uses: actions/upload-artifact@v4.0.0
      with:
        name: trivy-report
        path: report.json
    
    - name: Check Vuln Count
      id: vuln_count
      run: |
        report_file="report.json"
        vuln_count=$(jq '.Results | length' "$report_file")
        echo "vuln_count=$vuln_count" >> $GITHUB_OUTPUT
    
    - name: Copa Action
      if: steps.vuln_count.outputs.vuln_count != '0'
      id: copa
      uses: project-copacetic/copa-action@v1.0.1
      with:
        image: ${{ github.event.inputs.image }}
        image-report: 'report.json'
        patched-tag: 'patched'

    - name: container image push to ACR
      run: |
        image_name=$(echo ${{ github.event.inputs.image}} | sed -e 's/.*\///g')
        docker tag ${{ steps.copa.outputs.patched-image}} ${{ secrets.AZURE_ACR_NAME }}.azurecr.io/$image_name
        docker push ${{ secrets.AZURE_ACR_NAME }}.azurecr.io/$image_name
    
    - name: Get image digest
      id: digest
      run : |
        echo "DIGEST=$(az acr manifest list-metadata -r ${{ secrets.AZURE_ACR_NAME }} -n server --query [].digest -o tsv)" >> $GITHUB_OUTPUT

    - name: setup Notation CLI
      uses: notaryproject/notation-action/setup@v1
      with:
        version: 1.0.0
    - name: sign releasd artifact with signing plugin
      uses: notaryproject/notation-action/sign@v1
      with:
        plugin_name: azure-kv
        plugin_url:  https://github.com/Azure/notation-azure-kv/releases/download/v1.0.1/notation-azure-kv_1.0.1_linux_amd64.tar.gz
        plugin_checksum: f8a75d9234db90069d9eb5660e5374820edf36d710bd063f4ef81e7063d3810b
        key_id: ${{ secrets.AZURE_KV_NOTATION_KID }}
        target_artifact_reference: ${{ secrets.AZURE_ACR_NAME }}.azurecr.io/server@${{ steps.digest.outputs.DIGEST }} 
        signature_format: cose
        plugin_config: |-
          self_signed=true