name: terraform-validate
on:
  workflow_call:
    inputs:
        deploymentType:
            type: string
            description: Choose the target environment
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true

permissions:
      id-token: write
      contents: read
      pull-requests: write

jobs:
    terraform-validate:
        name: 'Terraform Plan'
        runs-on: ubuntu-latest
        defaults:
          run:
            shell: bash
            working-directory: 'IaC/${{ github.event.inputs.deploymentType}}'
        #env:
            #this is needed since we are running terraform with read-only permissions
            #ARM_SKIP_PROVIDER_REGISTRATION: true
    
        steps:
        # Checkout the repository to the GitHub Actions runner
        - name: Checkout
          uses: actions/checkout@v4.1.1
        
        - name: 'Az CLI login'
          uses: azure/login@v1.5.1
          with:
              client-id: ${{ secrets.AZURE_CLIENT_ID }}
              tenant-id: ${{ secrets.AZURE_TENANT_ID }}
              subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

        # Install the latest version of the Terraform CLI
        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v2.0.3
          with:
            terraform_wrapper: false
    
        - name: Terraform Init
          run: terraform init
      
        - name: Terraform Validate
          run: terraform validate
        
        - name: Terraform FMT
          run: terraform fmt -check