name: Trivy
on:

  workflow_dispatch:
    inputs:
      image:
        type: string
        description: Specify container image to scan
        required: true

permissions:
      id-token: write
      contents: read
      pull-requests: write

jobs:
  trivy:
    name: 'Trivy Scan'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1
    
    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: trivy
      uses: aquasecurity/trivy-action@0.16.0
      with:
        image-ref: ${{ github.event.inputs.image }}
        scan-type: 'image'
        format: table
        output: report.json
        exit-code: 1
        vuln-type: os
        severity: 'CRITICAL,HIGH'
        ignore-unfixed: true
        #ignore-policy: true
        #github-token: ${{ secrets.GITHUB_TOKEN }}